# Generated by Django 5.0.4 on 2024-05-07 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_initial'),
        ('projects', '0005_project_calendar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='widget',
            name='project',
            field=models.ForeignKey(default='632fe89d-7afe-4f8d-ac36-81fb51f63c5a', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
