# Generated by Django 5.0.4 on 2024-05-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_remove_widget_dashboard_widget_project_and_more'),
        ('projects', '0005_project_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='projects.project'),
        ),
    ]
