# Generated by Django 5.0.4 on 2024-04-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='first_names',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='last_names',
        ),
    ]
