# Generated by Django 5.0.4 on 2024-05-28 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('progress', models.FloatField(default=0)),
                ('calendar_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
