# Generated by Django 5.0.4 on 2024-06-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='widget_config',
            field=models.IntegerField(default=1877248),
            preserve_default=False,
        ),
    ]
