# Generated by Django 5.0.4 on 2024-04-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
