# Generated by Django 5.0.4 on 2024-04-06 20:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Not started'), (1, 'In progress'), (2, 'In review'), (3, 'Done')])),
                ('priority', models.SmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('dueDate', models.DateField()),
            ],
        ),
    ]
