# Generated by Django 5.0.4 on 2024-04-07 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateField(default=datetime.date(2024, 4, 7)),
            preserve_default=False,
        ),
    ]
