# Generated by Django 5.0.4 on 2024-04-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_priority_alter_task_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
