# Generated by Django 5.0.4 on 2024-04-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_asignee_alter_task_parent_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_id',
            field=models.CharField(default='mi calendario loco', max_length=32),
            preserve_default=False,
        ),
    ]
