# Generated by Django 5.0.4 on 2024-05-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asignee',
            new_name='assignee',
        ),
    ]
